### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by AJGG3000** [st-one-io/node-red-contrib-mpi-s7#3]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/gfcittolin/node-usb.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/root/.npm/_logs/2021-01-11T04_16_18_667Z-debug.log

**Comment by Matskk94** [comment]
Hello @gfcittolin ! 


Any updates regarding all the installation problems? Get problems when trying to install the palett or to it manually:
npm install node-red-contrib-mpi-s7

> usb@1.6.3 install /usr/src/node-red/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/bf2e0f-usb-v1.6.3-node-v64-linuxmusl-arm.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v64-linuxmusl-arm.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v64-linuxmusl-arm.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=10.24.1 runtime=node arch=arm libc=musl platform=linux)
make: Entering directory '/usr/src/node-red/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
   40 | #include <libudev.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [libusb.target.mk:140: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/usr/src/node-red/node_modules/usb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.10.63-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/node-red/node_modules/usb
gyp ERR! node -v v10.24.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@1.6.3 install: `prebuild-install --verbose || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usb@1.6.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-14T13_57_23_009Z-debug.log


Best regards,
Mats

**Comment by epgodoy** [comment]
Any update on the installation? Same errors of the others. Tks

**Comment by gwk1** [comment]
Fresh HA installation on Rpi3, installation fails via "manage palette":

-----------------------------------------------------------
2024-01-30T20:06:00.111Z Install : node-red-contrib-mpi-s7 1.0.0-beta.2

2024-01-30T20:06:00.168Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-mpi-s7@1.0.0-beta.2
2024-01-30T20:06:05.328Z [err] npm
2024-01-30T20:06:05.333Z [err]  
2024-01-30T20:06:05.333Z [err] WARN config production Use `--omit=dev` instead.
2024-01-30T20:06:15.765Z [err] npm
2024-01-30T20:06:15.766Z [err]  ERR! code 1
2024-01-30T20:06:15.768Z [err] npm
2024-01-30T20:06:15.769Z [err]  
2024-01-30T20:06:15.771Z [err] ERR!
2024-01-30T20:06:15.772Z [err]  path /config/node_modules/@gfcittolin/usb
2024-01-30T20:06:15.792Z [err] npm
2024-01-30T20:06:15.792Z [err]  ERR! command failed
2024-01-30T20:06:15.793Z [err] npm
2024-01-30T20:06:15.796Z [err]  ERR!
2024-01-30T20:06:15.797Z [err]  command sh -c node-gyp-build
2024-01-30T20:06:15.798Z [err] npm 
2024-01-30T20:06:15.798Z [err] ERR! gyp info it worked if it ends with ok
2024-01-30T20:06:15.798Z [err] npm ERR!
2024-01-30T20:06:15.799Z [err]  gyp info using node-gyp@10.0.1
2024-01-30T20:06:15.799Z [err] npm ERR! gyp info using node@18.19.0 | linux | arm64
2024-01-30T20:06:15.799Z [err] npm
2024-01-30T20:06:15.800Z [err]  ERR! gyp ERR! find Python 
2024-01-30T20:06:15.800Z [err] npm 
2024-01-30T20:06:15.800Z [err] ERR!
2024-01-30T20:06:15.802Z [err]  gyp ERR! find Python Python is not set from command line or npm configuration
2024-01-30T20:06:15.802Z [err] npm
2024-01-30T20:06:15.803Z [err]  ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2024-01-30T20:06:15.803Z [err] npm ERR! gyp ERR! find Python checking if "python3" can be used
2024-01-30T20:06:15.803Z [err] npm
2024-01-30T20:06:15.804Z [err]  ERR! gyp ERR! find Python - executable path is ""
2024-01-30T20:06:15.804Z [err] npm ERR! gyp ERR! find Python - "" could not be run
2024-01-30T20:06:15.804Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2024-01-30T20:06:15.804Z [err] npm 
2024-01-30T20:06:15.806Z [err] ERR! gyp ERR! find Python - executable path is ""
2024-01-30T20:06:15.806Z [err] npm ERR! gyp ERR! find Python - "" could not be run
2024-01-30T20:06:15.807Z [err] npm ERR! gyp ERR! find Python 
2024-01-30T20:06:15.807Z [err] npm ERR! gyp ERR! find Python **********************************************************
2024-01-30T20:06:15.807Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2024-01-30T20:06:15.807Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2024-01-30T20:06:15.807Z [err] npm ERR! gyp ERR! find Python you can try one of the following options:
2024-01-30T20:06:15.807Z [err] npm 
2024-01-30T20:06:15.808Z [err] ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2024-01-30T20:06:15.808Z [err] npm ERR! gyp ERR! find Python (accepted by both node-gyp and npm)
2024-01-30T20:06:15.808Z [err] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
2024-01-30T20:06:15.810Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2024-01-30T20:06:15.810Z [err] npm ERR! gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
2024-01-30T20:06:15.810Z [err] npm ERR!
2024-01-30T20:06:15.811Z [err]  gyp ERR! find Python For more information consult the documentation at:
2024-01-30T20:06:15.811Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2024-01-30T20:06:15.811Z [err] npm ERR! gyp ERR! find Python **********************************************************
2024-01-30T20:06:15.811Z [err] npm 
2024-01-30T20:06:15.812Z [err] ERR! gyp ERR! find Python 
2024-01-30T20:06:15.812Z [err] npm ERR! gyp ERR! configure error 
2024-01-30T20:06:15.812Z [err] npm ERR!
2024-01-30T20:06:15.813Z [err]  gyp ERR! stack Error: Could not find any Python installation to use
2024-01-30T20:06:15.813Z [err] npm ERR! gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
2024-01-30T20:06:15.813Z [err] npm ERR! gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
2024-01-30T20:06:15.813Z [err] npm 
2024-01-30T20:06:15.814Z [err] ERR! gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-30T20:06:15.814Z [err] npm ERR! gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:23:18)
2024-01-30T20:06:15.814Z [err] npm 
2024-01-30T20:06:15.814Z [err] ERR! gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
2024-01-30T20:06:15.814Z [err] npm ERR! gyp ERR! System Linux 6.1.63-haos-raspi
2024-01-30T20:06:15.814Z [err] npm 
2024-01-30T20:06:15.815Z [err] ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2024-01-30T20:06:15.815Z [err] npm ERR! gyp ERR! cwd /config/node_modules/@gfcittolin/usb
2024-01-30T20:06:15.815Z [err] npm
2024-01-30T20:06:15.821Z [err]  ERR! gyp ERR! node -v v18.19.0
2024-01-30T20:06:15.821Z [err] npm ERR! gyp ERR! node-gyp -v v10.0.1
2024-01-30T20:06:15.821Z [err] npm ERR! gyp ERR! not ok
2024-01-30T20:06:15.841Z [err] 
2024-01-30T20:06:15.843Z [err] npm 
2024-01-30T20:06:15.844Z [err] ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-01-30T20_06_04_748Z-debug-0.log
2024-01-30T20:06:15.951Z rc=1
